### ISSUE TITLE
PLS-X stage with external control

### ISSUE THREAD

**Issue by edwardando** [amsikking/thorlabs_MCM3000#5]
Hi there, 
Before I write in Issue #4, we're trying to integrate the PLS-X stage on an MCM3001 controller.
It's going nicely although this controller also has an external control plugged into it...
![2024-01-29-11-56-54-020](https://github.com/amsikking/thorlabs_MCM3000/assets/2989690/5d8c70b0-e71b-4bd1-a9a0-93aa9763c7ae)
![2024-01-29-11-56-25-720](https://github.com/amsikking/thorlabs_MCM3000/assets/2989690/64d5c7a2-ab24-4f45-a792-1a4e9e88377a)
this causes some havoc because this loves the stage without this software understanding it.
This means that if:
- class is instantiated with Z=3000
- external controller is used to move stage to Z=4000
- relative move is made in software +100
...the relative move is with respect to the instantiated initial position, and thus is Z=3100.
This is obviously annoying,  but we believe that a `_get_encoder_counts` → `_encoder_counts_to_um` 
to update `self.position_um` in line 166 should do the job, do you agree?

Also we have some old version of this code that exposed `get_position_um` which was jolly useful, can you/we reinstate it?

**Comment by amsikking** [comment]
Hi Edward, thanks for the detailed comment and recommendation.

After a quick look I agree with your suggestion. I don't update hardware device adaptors without testing them, so I'll try this next time I'm in the lab (maybe next week). If you can test your addition at 166 in the meantime that would help (I'll assume it works unless I hear otherwise). Yes we can add the 'convenience' method 'get_position_um'.

Thanks again,

A.

**Comment by amsikking** [comment]
Hi Edward, thanks for your contribution! I tested it (just to be sure) and it seems functionally correct. I merged your pull request and may follow up with some cosmetic tidy up. Thanks again, A.
